# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Acquia QA'
tagline:          'Acquia QA'
paginate:         5
baseurl:          '/acquiaqa'
